config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'dashboard#show'
  get '/test' => 'test#show'

  resources :sites, only: [:new, :create, :show] do
    resources :editable_regions, as: :editable_region do
      resources :versions, only: [:show, :new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :version_collections, only: [:index]
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :editable_region
  validates :content, presence: true

  def to_html
    MarkdownParser.render(self.content)
  end

  def self.create_new_version?(region:, params:)
    latest_version = region.latest_version
    if latest_version.content != params['content']
      region.versions.create(content: params['content'])
    end
    true
  end

  def convert_and_save
    html = to_html
    self.html_content = html
    self.converted = true
    self.save
    html
  end

  def html
    self.converted ? self.html_content : self.convert_and_save
  end

end

app/controllers/versions_controller.rb
class VersionsController < SitePermissionController
  def new
    @region = EditableRegion.find(params[:editable_region_id])
  end

  def create
    region = EditableRegion.find(params['editable_region_id'])
    if Version.create_new_version?(region: region, params: params)
      flash_and_redirect site_editable_region_index_path(region.site_id),
        success: 'Your new version has been saved successfully!'
    else
      render :new
    end
  end
end

app/views/versions/new.html.slim
.row
  .col-xs-12.page-title
    h2= "#{@region.site.name}: #{@region.name}"

.row
  .col-xs-12
    = bootstrap_form_tag url: site_editable_region_versions_path, :method => :post do |f|
      = f.text_area :content, hide_label: true, id: 'md-content-area', value: @region.latest_version.content
      = f.submit 'Create Editable Region', class: 'btn btn-primary'

javascript:
  $(document).ready(function() {
    var mde = new SimpleMDE({ element: document.getElementById("md-content-area") });
  });