config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'dashboard#show'
  get '/test' => 'test#show'

  resources :sites, only: [:new, :create, :show] do
    resources :editable_regions, as: :editable_region do
      resources :versions, only: [:show, :new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :version_collections, only: [:index]
    end
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/editable_region.rb
class EditableRegion < ActiveRecord::Base
  belongs_to :site
  has_many :versions

  validates :name, presence: true, uniqueness: {:scope => :site_id}

  default_scope { order(:name => :asc) }

  enum region_type: [:basic, :specific]

  def latest_version
    versions = self.versions
    versions.any? ? versions.last : nil
  end
end

app/controllers/editable_regions_controller.rb
class EditableRegionsController < SitePermissionController
  before_action :set_site

  def index
  end

  def new
    @region = @site.editable_regions.new
  end

  def create
    @erv = EditableRegionVersion.new(user: current_user, params: params)
    if @erv.create_region_and_version
      flash_and_redirect(site_editable_region_index_path(params[:site_id]), success: 'Your region has been created!')
    else
      flash_and_render(:new, danger: 'Sorry, your editable region could not be created.')
    end
  end

  def show
    @region = EditableRegion.find(params[:id])
  end

  private

  def set_site
    @site = current_user.sites.find(params[:site_id])
  end
end

app/views/editable_regions/index.html.slim
.row.page-title
  .col-xs-8
      h2= "#{@site.name}: Regions"
      p.url = @site.url
  .col-xs-4.text-right
    h2
      button type="button" class="btn btn-default btn-md" data-toggle="modal" data-target="#embed-code-modal"
        | Get Embed Code

.row
  - if @site.regions.any?
      - @site.regions.each do |region|
        = render partial: 'shared/item_box',
          locals: {name: region.name,
          link: new_site_editable_region_version_path(region.site_id, region.id),
          button_text: 'Edit'}

  .col-sm-3.item-box.item-box-link
    .item-name
      strong Create a new region
    = link_to 'New Region', new_site_editable_region_path(@site.id), class: 'btn btn-primary'

= content_for :end_of_body
  .modal.modal-sm.fade#embed-code-modal role="dialog"
    .modal-daialog role="document"
      .modal-content
        .modal-header
          button type="button" class="close" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true" &times;
          h4.modal-title Site Embed Code
        .modal-body
          textarea.disabled.form-control rows="4" readonly="readonly"
            = @site.read_script

app/views/editable_regions/new.html.slim
.row
  .col-sm-6
    h2= "#{@region.site.name}: New Region"

.row
  .col-xs-12
    = bootstrap_form_tag url: site_editable_region_index_path, :method => :post do |f|
      = f.text_field :name
      = f.text_area :content, id: 'md-content-area', hide_label: true
      = f.select :region_type, [['Basic', :basic], ['Specific', :specific]]
      = f.submit 'Create Editable Region', class: 'btn btn-primary'

javascript:
  $(document).ready(function() {
    var mde = new SimpleMDE({ element: document.getElementById("md-content-area") });
  });

app/views/editable_regions/show.html.slim
.row
  .col-sm-6
    h2= "#{@region.site.name}: #{@region.name}"
    strong Type:
    span= " #{@region.region_type.capitalize}"


- @region.versions.each do |version|
  .row
    .col-xs-12
     = version.html.html_safe